/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Aplicacion;

import Persistencia.ConexionOracle;
import Persistencia.Log;
import Persistencia.ManejaColabora;
import Persistencia.ManejaLog;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author borja
 */
public class VentanaGestionLog extends java.awt.Frame {

    private final ConexionOracle conexion;
    private final DefaultTableModel mColaboraciones;

    private final ManejaLog ml;
    
    /**
     * Creates new form ventanaExpetos
     *
     * @param conexion
     */
    public VentanaGestionLog(ConexionOracle conexion) {
        initComponents();
        setLocationRelativeTo(getParent());
        setTitle("Gestionar Logs");
        setResizable(false);

        this.conexion = conexion;
        ml = new ManejaLog(conexion);

        mColaboraciones = new DefaultTableModel();
        jTableColaboraciones.setModel(mColaboraciones);
        String[] nombreColumnas = {"Usuario", "Fecha", "Operacion", "Tabla"};
        mColaboraciones.setColumnIdentifiers(nombreColumnas);
        jTableColaboraciones.getTableHeader().setResizingAllowed(false);
        jTableColaboraciones.getColumnModel().getColumn(0).setPreferredWidth(100);
        jTableColaboraciones.getColumnModel().getColumn(1).setPreferredWidth(150);
        jTableColaboraciones.getColumnModel().getColumn(2).setPreferredWidth(125);
        jTableColaboraciones.getColumnModel().getColumn(3).setPreferredWidth(125);
        
        cargarLogs();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableColaboraciones = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButtonLimpiar = new javax.swing.JButton();
        actualizar = new javax.swing.JButton();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        jTableColaboraciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableColaboraciones);

        jLabel1.setText("Log");

        jButtonLimpiar.setText("Limpiar");
        jButtonLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimpiarActionPerformed(evt);
            }
        });

        actualizar.setText("Actualizar");
        actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(196, 196, 196)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButtonLimpiar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(actualizar))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonLimpiar)
                    .addComponent(actualizar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        dispose();
    }//GEN-LAST:event_exitForm

    /**
     * Muestra las colaboraciones del caso introducido
     *
     * @param evt
     */
    private void jButtonLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimpiarActionPerformed
        try {
            ml.limpiarLogs();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Error al limpiar logs", JOptionPane.ERROR_MESSAGE);
        }
        cargarLogs();
    }//GEN-LAST:event_jButtonLimpiarActionPerformed

    private void actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizarActionPerformed
        cargarLogs();
    }//GEN-LAST:event_actualizarActionPerformed

    /**
     * Limpia la tabla de colaboraciones
     */
    private void limpiarTabla() {
        while (mColaboraciones.getRowCount() > 0) {
            mColaboraciones.removeRow(0);
        }
    }
    
    private void cargarLogs(){
        limpiarTabla();
        try {
            ArrayList<Log> logs = ml.listaLogs();
            for (Log log : logs) {
                mColaboraciones.addRow(new String[]{log.getUsuario(), log.getFecha(), log.getOperacion(), log.getTabla()});
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Error al mostrar logs", JOptionPane.ERROR_MESSAGE);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton actualizar;
    private javax.swing.JButton jButtonLimpiar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableColaboraciones;
    // End of variables declaration//GEN-END:variables
}
