package patronfactorypractica.interfaz;

import javax.swing.DefaultListModel;
import javax.swing.JList;
import patronfactorypractica.Factoria;
import patronfactorypractica.FactoriaRelojes;
import patronfactorypractica.Reloj;

public class MenuPrincipal extends javax.swing.JFrame {

    private final DefaultListModel lmFactorias;
    
    public MenuPrincipal() {
        initComponents();
        radioDMA12.setActionCommand("DMA12h");
        radioDMA24.setActionCommand("DMA24h");
        radioMDA12.setActionCommand("MDA12h");
        radioMDA24.setActionCommand("MDA24h");
        radioISO.setActionCommand("ISO");
        radioISOUTC.setActionCommand("ISOUTC");
        lmFactorias = new DefaultListModel();
        listFactorias.setModel(lmFactorias);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        groupTipoReloj = new javax.swing.ButtonGroup();
        btnCrearFactoria = new javax.swing.JButton();
        radioDMA12 = new javax.swing.JRadioButton();
        radioDMA24 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listFactorias = new javax.swing.JList<>();
        radioMDA12 = new javax.swing.JRadioButton();
        radioMDA24 = new javax.swing.JRadioButton();
        radioISOUTC = new javax.swing.JRadioButton();
        radioISO = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Patron Factory");

        btnCrearFactoria.setText("Crear factoria");
        btnCrearFactoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearFactoriaActionPerformed(evt);
            }
        });

        groupTipoReloj.add(radioDMA12);
        radioDMA12.setText("Reloj DMA 12h");

        groupTipoReloj.add(radioDMA24);
        radioDMA24.setText("Reloj DMA 24h");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Crear factoria");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Factorias");

        listFactorias.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listFactoriasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(listFactorias);

        groupTipoReloj.add(radioMDA12);
        radioMDA12.setText("Reloj DMA 12h");

        groupTipoReloj.add(radioMDA24);
        radioMDA24.setText("Reloj MDA 24h");

        groupTipoReloj.add(radioISOUTC);
        radioISOUTC.setText("Reloj ISO UTC");

        groupTipoReloj.add(radioISO);
        radioISO.setText("Reloj ISO");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(radioMDA24, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(radioMDA12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(radioISO)
                                    .addComponent(radioISOUTC)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(radioDMA24)
                                    .addComponent(radioDMA12))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(30, 30, 30))
                    .addComponent(btnCrearFactoria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(radioDMA12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(radioDMA24)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(radioMDA12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(radioMDA24)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(radioISO)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(radioISOUTC)
                        .addGap(18, 18, 18)
                        .addComponent(btnCrearFactoria))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearFactoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearFactoriaActionPerformed
        lmFactorias.addElement(new FactoriaRelojes(groupTipoReloj.getSelection().getActionCommand()));
    }//GEN-LAST:event_btnCrearFactoriaActionPerformed

    private void listFactoriasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listFactoriasMouseClicked
        JList list = (JList) evt.getSource();
        if (evt.getClickCount() == 2) {
            int index = list.locationToIndex(evt.getPoint());
            Factoria factoria = (Factoria) lmFactorias.get(index);
            
            VentanaReloj ventanaReloj = new VentanaReloj(factoria.crearReloj());
            ventanaReloj.setLocationRelativeTo(this);
            ventanaReloj.setVisible(true);
        }
    }//GEN-LAST:event_listFactoriasMouseClicked

   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrearFactoria;
    private javax.swing.ButtonGroup groupTipoReloj;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<Reloj> listFactorias;
    private javax.swing.JRadioButton radioDMA12;
    private javax.swing.JRadioButton radioDMA24;
    private javax.swing.JRadioButton radioISO;
    private javax.swing.JRadioButton radioISOUTC;
    private javax.swing.JRadioButton radioMDA12;
    private javax.swing.JRadioButton radioMDA24;
    // End of variables declaration//GEN-END:variables
}
