/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Aplicacion;

import Persistencia.conexionOracle;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author borja
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    private conexionOracle conexion;

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
        setTitle("DDSI Practica 3 Borja López Pineda");
        setLocationRelativeTo(null);
        (new Thread() {
            @Override
            public void run() {
                try {
                    conexion = new conexionOracle();
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(null, ex.getMessage());
                    System.exit(0);
                }
            }
        }).start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuPrincipal = new javax.swing.JMenuBar();
        jMenuConexion = new javax.swing.JMenu();
        jMenuConexionSalir = new javax.swing.JMenuItem();
        jMenuExpertos = new javax.swing.JMenu();
        jMenuExertosGestion = new javax.swing.JMenuItem();
        jMenuCasos = new javax.swing.JMenu();
        jMenuColaboraciones = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jMenuConexion.setText("Conexión");

        jMenuConexionSalir.setText("Salir aplicación");
        jMenuConexionSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuConexionSalirActionPerformed(evt);
            }
        });
        jMenuConexion.add(jMenuConexionSalir);

        jMenuPrincipal.add(jMenuConexion);

        jMenuExpertos.setText("Expertos");

        jMenuExertosGestion.setText("Gestión de expertos");
        jMenuExertosGestion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuExertosGestionActionPerformed(evt);
            }
        });
        jMenuExpertos.add(jMenuExertosGestion);

        jMenuPrincipal.add(jMenuExpertos);

        jMenuCasos.setText("Casos policiales");
        jMenuPrincipal.add(jMenuCasos);

        jMenuColaboraciones.setText("Colaboraciones");
        jMenuPrincipal.add(jMenuColaboraciones);

        setJMenuBar(jMenuPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuConexionSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuConexionSalirActionPerformed
        cerrarConexion();
        System.exit(0);
    }//GEN-LAST:event_jMenuConexionSalirActionPerformed

    private void jMenuExertosGestionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuExertosGestionActionPerformed
        ventanaExpetos vE = new ventanaExpetos(conexion);
        vE.setVisible(true);
    }//GEN-LAST:event_jMenuExertosGestionActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        cerrarConexion();
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }
    
    private void cerrarConexion(){
        try {
            if(conexion != null)
                conexion.desconexion();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenuCasos;
    private javax.swing.JMenu jMenuColaboraciones;
    private javax.swing.JMenu jMenuConexion;
    private javax.swing.JMenuItem jMenuConexionSalir;
    private javax.swing.JMenuItem jMenuExertosGestion;
    private javax.swing.JMenu jMenuExpertos;
    private javax.swing.JMenuBar jMenuPrincipal;
    // End of variables declaration//GEN-END:variables
}
