package patronsingletronpractica.interfaz;

import javax.swing.JOptionPane;
import patronsingletronpractica.Usuario;
import patronsingletronpractica.Avion;
import patronsingletronpractica.ReservaExceotion;

public class ComprarBilletes extends javax.swing.JFrame {

    private final Usuario usuario;
    private final Avion avion;
    private final MenuPrincipal padre;
    
    public ComprarBilletes(Usuario usuario, Avion avion, MenuPrincipal padre) {
        this.usuario = usuario;
        this.avion = avion;
        this.padre = padre;
        initComponents();
        labelDNI.setText("<html><body><b>Usuario: </b>"+usuario.toString()+"</body></html>");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelDNI = new javax.swing.JLabel();
        inputNumero = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnComprar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        labelDNI.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelDNI.setText("Usuario: ");

        jLabel2.setText("Número de billetes");

        btnComprar.setText("Comprar");
        btnComprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelDNI, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(inputNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnComprar)
                        .addGap(0, 80, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelDNI)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnComprar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnComprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprarActionPerformed
        try {
            int billetes = Integer.parseInt(inputNumero.getText());
            usuario.QuieroComprarBilletes(billetes);
            dispose();
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "El número de billetes introducido no es válido: "+ex.getMessage(), "Error al comprar billetes", JOptionPane.ERROR_MESSAGE);
        } catch (ReservaExceotion ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error al comprar billetes", JOptionPane.ERROR_MESSAGE);
        }finally{
            inputNumero.setText("");
            padre.actualizarTablaReservas();
        }
    }//GEN-LAST:event_btnComprarActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnComprar;
    private javax.swing.JTextField inputNumero;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel labelDNI;
    // End of variables declaration//GEN-END:variables
}
