package patronsingletronpractica.interfaz;

import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import patronsingletronpractica.Avion;
import patronsingletronpractica.Agencia;
import patronsingletronpractica.ReservaExceotion;
import patronsingletronpractica.Usuario;

public class DevolverBilletes extends javax.swing.JFrame {

    private final Agencia agencia;
    private final Avion avion;
    private final MenuPrincipal padre;
    public DevolverBilletes(Agencia agencia, Avion avion, MenuPrincipal padre) {
        this.agencia = agencia;
        this.avion = avion;
        this.padre = padre;
        initComponents();
        labelNombre.setText("<html><body><b>Agencia: </b>"+agencia.toString()+"</body></html>");
        List<Usuario> usuarios = padre.obtenerUsuarios();
        DefaultComboBoxModel model = (DefaultComboBoxModel) comboUsuarios.getModel();
        model.removeAllElements();
        for (Usuario usuario : usuarios) {
            model.addElement(usuario);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelNombre = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        inputNumero = new javax.swing.JTextField();
        btnDevolver = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        comboUsuarios = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        labelNombre.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelNombre.setText("Agencia: ");

        jLabel2.setText("Número de billetes");

        btnDevolver.setText("Devolver");
        btnDevolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDevolverActionPerformed(evt);
            }
        });

        jLabel3.setText("Usuario");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(inputNumero, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnDevolver))
                            .addComponent(comboUsuarios, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(labelNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelNombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDevolver))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDevolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDevolverActionPerformed
        try {
            Usuario usuario = (Usuario) comboUsuarios.getSelectedItem();
            int billetes = Integer.parseInt(inputNumero.getText());
            agencia.QuieroDevolverBilletes(billetes, usuario);
            dispose();
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "El número de billetes introducido no es válido: "+ex.getMessage(), "Error al comprar billetes", JOptionPane.ERROR_MESSAGE);
        } catch (ReservaExceotion ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error al devolver billetes", JOptionPane.ERROR_MESSAGE);
        }finally{
            inputNumero.setText("");
            padre.actualizarTablaReservas();
        }
    }//GEN-LAST:event_btnDevolverActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDevolver;
    private javax.swing.JComboBox<Usuario> comboUsuarios;
    private javax.swing.JTextField inputNumero;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel labelNombre;
    // End of variables declaration//GEN-END:variables
}
