/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "GestorAlmacenes.h"

bool_t
xdr_Cadena (XDR *xdrs, Cadena objp)
{
	register int32_t *buf;

	 if (!xdr_vector (xdrs, (char *)objp, 90,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_TFecha (XDR *xdrs, TFecha *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->Dia))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->Mes))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->Anyo))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_TProducto (XDR *xdrs, TProducto *objp)
{
	register int32_t *buf;

	 if (!xdr_Cadena (xdrs, objp->CodProducto))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->Cantidad))
		 return FALSE;
	 if (!xdr_Cadena (xdrs, objp->NombreProducto))
		 return FALSE;
	 if (!xdr_float (xdrs, &objp->Precio))
		 return FALSE;
	 if (!xdr_Cadena (xdrs, objp->Descripcion))
		 return FALSE;
	 if (!xdr_TFecha (xdrs, &objp->Caducidad))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_TDatosAlmacen (XDR *xdrs, TDatosAlmacen *objp)
{
	register int32_t *buf;

	 if (!xdr_Cadena (xdrs, objp->Nombre))
		 return FALSE;
	 if (!xdr_Cadena (xdrs, objp->Direccion))
		 return FALSE;
	 if (!xdr_Cadena (xdrs, objp->Fichero))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_TBusProd (XDR *xdrs, TBusProd *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->Almacen))
		 return FALSE;
	 if (!xdr_Cadena (xdrs, objp->CodProducto))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_TObtProd (XDR *xdrs, TObtProd *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->Almacen))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->PosProducto))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_TActProd (XDR *xdrs, TActProd *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->Almacen))
		 return FALSE;
	 if (!xdr_TProducto (xdrs, &objp->Producto))
		 return FALSE;
	return TRUE;
}
