/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Aplicacion;

import Persistencia.ConexionOracle;
import java.awt.event.WindowAdapter;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author borja
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    private ConexionOracle conexion;

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
        setTitle("DDSI Proyecto Borja López Pineda");
        setLocationRelativeTo(null);
        setResizable(false);

        jMenuGestionExertos.setEnabled(false);
        jMenuBuscarColaboradores.setEnabled(false);
        jMenuGestionColaboraciones.setEnabled(false);
        jMenuGestionGlobalBD.setEnabled(false);
        jMenuCerrar.setEnabled(false);
    }

    public void setConexion(ConexionOracle c) {
        cerrarConexion();
        conexion = c;
        jLabelConectando.setVisible(false);
        jMenuGestionExertos.setEnabled(true);
        jMenuBuscarColaboradores.setEnabled(true);
        jMenuGestionColaboraciones.setEnabled(true);
        jMenuGestionGlobalBD.setEnabled(true);
        jMenuCerrar.setEnabled(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelConectando = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuPrincipal = new javax.swing.JMenuBar();
        jMenuConexion = new javax.swing.JMenu();
        jMenuIniciar = new javax.swing.JMenuItem();
        jMenuCerrar = new javax.swing.JMenuItem();
        jMenuSalir = new javax.swing.JMenuItem();
        jMenuExpertos = new javax.swing.JMenu();
        jMenuGestionExertos = new javax.swing.JMenuItem();
        jMenuCasos = new javax.swing.JMenu();
        jMenuColaboraciones = new javax.swing.JMenu();
        jMenuBuscarColaboradores = new javax.swing.JMenuItem();
        jMenuGestionColaboraciones = new javax.swing.JMenuItem();
        jMenuGestionCompleta = new javax.swing.JMenu();
        jMenuGestionGlobalBD = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabelConectando.setText("Desconectado");

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/fondo.png"))); // NOI18N
        jLabel1.setText("jLabel1");

        jMenuConexion.setText("Conexión");

        jMenuIniciar.setText("Iniciar sesión");
        jMenuIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuIniciarActionPerformed(evt);
            }
        });
        jMenuConexion.add(jMenuIniciar);

        jMenuCerrar.setText("Cerrar sesion");
        jMenuCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCerrarActionPerformed(evt);
            }
        });
        jMenuConexion.add(jMenuCerrar);

        jMenuSalir.setText("Salir aplicación");
        jMenuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuSalirActionPerformed(evt);
            }
        });
        jMenuConexion.add(jMenuSalir);

        jMenuPrincipal.add(jMenuConexion);

        jMenuExpertos.setText("Expertos");

        jMenuGestionExertos.setText("Gestión de expertos");
        jMenuGestionExertos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuGestionExertosActionPerformed(evt);
            }
        });
        jMenuExpertos.add(jMenuGestionExertos);

        jMenuPrincipal.add(jMenuExpertos);

        jMenuCasos.setText("Casos policiales");
        jMenuPrincipal.add(jMenuCasos);

        jMenuColaboraciones.setText("Colaboraciones");

        jMenuBuscarColaboradores.setText("Buscar Colaboradores");
        jMenuBuscarColaboradores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuBuscarColaboradoresActionPerformed(evt);
            }
        });
        jMenuColaboraciones.add(jMenuBuscarColaboradores);

        jMenuGestionColaboraciones.setText("Gestión de Colaboraciones");
        jMenuGestionColaboraciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuGestionColaboracionesActionPerformed(evt);
            }
        });
        jMenuColaboraciones.add(jMenuGestionColaboraciones);

        jMenuPrincipal.add(jMenuColaboraciones);

        jMenuGestionCompleta.setText("Gestión Completa");

        jMenuGestionGlobalBD.setText("Gestión Global de la BD");
        jMenuGestionGlobalBD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuGestionGlobalBDActionPerformed(evt);
            }
        });
        jMenuGestionCompleta.add(jMenuGestionGlobalBD);

        jMenuPrincipal.add(jMenuGestionCompleta);

        setJMenuBar(jMenuPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 775, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(349, 349, 349)
                .addComponent(jLabelConectando)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelConectando)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuSalirActionPerformed
        cerrarConexion();
        System.exit(0);
    }//GEN-LAST:event_jMenuSalirActionPerformed

    /**
     * Abre la venta de gestión de expertos Cierra la ventana principal, hasta
     * que se cierre la secundaria
     *
     * @param evt
     */
    private void jMenuGestionExertosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuGestionExertosActionPerformed
        VentanaGestionExpertos vE = new VentanaGestionExpertos(conexion);
        vE.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosed(java.awt.event.WindowEvent windowEvent) {
                setVisible(true);
            }
        });
        setVisible(false);
        vE.setVisible(true);
    }//GEN-LAST:event_jMenuGestionExertosActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosed

    /**
     * Siempre que se cierra la ventana principal, se debe terminar la conexión
     *
     * @param evt
     */
    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        cerrarConexion();
    }//GEN-LAST:event_formWindowClosing

    /**
     * Abre la venta de gestión de colaboraciones Cierra la ventana principal,
     * hasta que se cierre la secundaria
     *
     * @param evt
     */
    private void jMenuGestionColaboracionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuGestionColaboracionesActionPerformed
        VentanaGestionColaboraciones vC = new VentanaGestionColaboraciones(conexion);
        vC.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosed(java.awt.event.WindowEvent windowEvent) {
                setVisible(true);
            }
        });
        setVisible(false);
        vC.setVisible(true);
    }//GEN-LAST:event_jMenuGestionColaboracionesActionPerformed

    /**
     * Abre la venta de busqueda de colaboraciones Cierra la ventana principal,
     * hasta que se cierre la secundaria
     *
     * @param evt
     */
    private void jMenuBuscarColaboradoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuBuscarColaboradoresActionPerformed
        VentanaBuscarColaboraciones vBC = new VentanaBuscarColaboraciones(conexion);
        vBC.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosed(java.awt.event.WindowEvent windowEvent) {
                setVisible(true);
            }
        });
        setVisible(false);
        vBC.setVisible(true);
    }//GEN-LAST:event_jMenuBuscarColaboradoresActionPerformed

    /**
     * Abre la venta de gestión global Cierra la ventana principal, hasta que se
     * cierre la secundaria
     *
     * @param evt
     */
    private void jMenuGestionGlobalBDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuGestionGlobalBDActionPerformed
        VentanaGestionGlobal vGG = new VentanaGestionGlobal(conexion);
        vGG.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosed(java.awt.event.WindowEvent windowEvent) {
                setVisible(true);
            }
        });
        setVisible(false);
        vGG.setVisible(true);
    }//GEN-LAST:event_jMenuGestionGlobalBDActionPerformed

    private void jMenuIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuIniciarActionPerformed
        VentanaInicioSesion vIS = new VentanaInicioSesion(this);
        vIS.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosed(java.awt.event.WindowEvent windowEvent) {
                setVisible(true);
            }
        });
        setVisible(false);
        vIS.setVisible(true);
    }//GEN-LAST:event_jMenuIniciarActionPerformed

    private void jMenuCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCerrarActionPerformed
        cerrarConexion();
        jLabelConectando.setVisible(true);
        jMenuGestionExertos.setEnabled(false);
        jMenuBuscarColaboradores.setEnabled(false);
        jMenuGestionColaboraciones.setEnabled(false);
        jMenuGestionGlobalBD.setEnabled(false);
        jMenuCerrar.setEnabled(false);
    }//GEN-LAST:event_jMenuCerrarActionPerformed

    /**
     * Crea la ventana principoal y la muestra
     *
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    /**
     * Intenta cerra la conexión
     */
    private void cerrarConexion() {
        try {
            if (conexion != null) {
                conexion.desconexion();
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Error al cerrar conexión", JOptionPane.ERROR_MESSAGE);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelConectando;
    private javax.swing.JMenuItem jMenuBuscarColaboradores;
    private javax.swing.JMenu jMenuCasos;
    private javax.swing.JMenuItem jMenuCerrar;
    private javax.swing.JMenu jMenuColaboraciones;
    private javax.swing.JMenu jMenuConexion;
    private javax.swing.JMenu jMenuExpertos;
    private javax.swing.JMenuItem jMenuGestionColaboraciones;
    private javax.swing.JMenu jMenuGestionCompleta;
    private javax.swing.JMenuItem jMenuGestionExertos;
    private javax.swing.JMenuItem jMenuGestionGlobalBD;
    private javax.swing.JMenuItem jMenuIniciar;
    private javax.swing.JMenuBar jMenuPrincipal;
    private javax.swing.JMenuItem jMenuSalir;
    // End of variables declaration//GEN-END:variables
}
