/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cliente;

import comun.DatosAlmacen;
import comun.IGestionAlmacenes;
import java.rmi.RemoteException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author borja
 */
public class MenuPrincipal extends javax.swing.JFrame {

    private final IGestionAlmacenes stub;
    private DatosAlmacen actual;

    public MenuPrincipal(IGestionAlmacenes stub) {
        this.stub = stub;
        initComponents();
        actualizarActual();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelAbierto = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        itemCrearAlmacen = new javax.swing.JMenuItem();
        itemAbrirAlmacen = new javax.swing.JMenuItem();
        itemCerrarAlmacen = new javax.swing.JMenuItem();
        itemGuardarDatos = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        itemListarProductos = new javax.swing.JMenuItem();
        itemConsultarProducto = new javax.swing.JMenuItem();
        itemAnadirProducto = new javax.swing.JMenuItem();
        itemActualizarProducto = new javax.swing.JMenuItem();
        itemEliminarProducto = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Practica 2 SD Borja López");
        setAlwaysOnTop(true);
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));

        labelAbierto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelAbierto.setText("Almacen abierto");

        jMenu1.setText("Almacen");

        itemCrearAlmacen.setText("Crear almacen");
        itemCrearAlmacen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCrearAlmacenActionPerformed(evt);
            }
        });
        jMenu1.add(itemCrearAlmacen);

        itemAbrirAlmacen.setText("Abrir almacen");
        itemAbrirAlmacen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemAbrirAlmacenActionPerformed(evt);
            }
        });
        jMenu1.add(itemAbrirAlmacen);

        itemCerrarAlmacen.setText("Cerrar almacen");
        itemCerrarAlmacen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCerrarAlmacenActionPerformed(evt);
            }
        });
        jMenu1.add(itemCerrarAlmacen);

        itemGuardarDatos.setText("Guardar datos");
        itemGuardarDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemGuardarDatosActionPerformed(evt);
            }
        });
        jMenu1.add(itemGuardarDatos);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Productos");

        itemListarProductos.setText("Listar productos");
        itemListarProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemListarProductosActionPerformed(evt);
            }
        });
        jMenu2.add(itemListarProductos);

        itemConsultarProducto.setText("Consultar producto");
        itemConsultarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemConsultarProductoActionPerformed(evt);
            }
        });
        jMenu2.add(itemConsultarProducto);

        itemAnadirProducto.setText("Añadir producto");
        itemAnadirProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemAnadirProductoActionPerformed(evt);
            }
        });
        jMenu2.add(itemAnadirProducto);

        itemActualizarProducto.setText("Actualizar producto");
        itemActualizarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemActualizarProductoActionPerformed(evt);
            }
        });
        jMenu2.add(itemActualizarProducto);

        itemEliminarProducto.setText("Eliminar producto");
        itemEliminarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemEliminarProductoActionPerformed(evt);
            }
        });
        jMenu2.add(itemEliminarProducto);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelAbierto, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelAbierto)
                .addContainerGap(94, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemCrearAlmacenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCrearAlmacenActionPerformed
        new CrearAlmacen(stub, this);
    }//GEN-LAST:event_itemCrearAlmacenActionPerformed

    private void itemAbrirAlmacenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAbrirAlmacenActionPerformed
        new AbrirAlmacen(stub, this);
    }//GEN-LAST:event_itemAbrirAlmacenActionPerformed

    private void itemCerrarAlmacenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCerrarAlmacenActionPerformed
        try {
            stub.guardarAlmacen(actual.getFichero());
            stub.cerrarAlmacen(actual.getFichero());
            actual = null;
            actualizarActual();
        } catch (RemoteException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Error al cerrar almacen", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_itemCerrarAlmacenActionPerformed

    private void itemGuardarDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemGuardarDatosActionPerformed
        try {
            stub.guardarAlmacen(actual.getFichero());
        } catch (RemoteException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Error al guardar almacen", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_itemGuardarDatosActionPerformed

    private void itemListarProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemListarProductosActionPerformed
        new ListarProductos(stub, this);
    }//GEN-LAST:event_itemListarProductosActionPerformed

    private void itemConsultarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemConsultarProductoActionPerformed
        new ConsultarProducto(stub, this);
    }//GEN-LAST:event_itemConsultarProductoActionPerformed

    private void itemAnadirProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAnadirProductoActionPerformed
        new AnadirProducto(stub, this);
    }//GEN-LAST:event_itemAnadirProductoActionPerformed

    private void itemActualizarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemActualizarProductoActionPerformed
        new ActualizarProducto(stub, this);
    }//GEN-LAST:event_itemActualizarProductoActionPerformed

    private void itemEliminarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemEliminarProductoActionPerformed
        new EliminarProducto(stub, this);
    }//GEN-LAST:event_itemEliminarProductoActionPerformed

    public void setActual(DatosAlmacen actual) {
        this.actual = actual;
        actualizarActual();
    }

    public DatosAlmacen getActual() {
        return actual;
    }

    private void actualizarActual() {
        if (actual == null) {
            labelAbierto.setText("Sin almacen abierto");
        } else {
            labelAbierto.setText("<html><body>Almacen abierto: " + actual.getNombre() + "<br>Direccion: " + actual.getDireccion() + "<br>Fichero: " + actual.getFichero() + "</body></html>");
        }
        itemListarProductos.setEnabled(actual != null);
        itemGuardarDatos.setEnabled(actual != null);
        itemEliminarProducto.setEnabled(actual != null);
        itemConsultarProducto.setEnabled(actual != null);
        itemCerrarAlmacen.setEnabled(actual != null);
        itemAnadirProducto.setEnabled(actual != null);
        itemActualizarProducto.setEnabled(actual != null);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem itemAbrirAlmacen;
    private javax.swing.JMenuItem itemActualizarProducto;
    private javax.swing.JMenuItem itemAnadirProducto;
    private javax.swing.JMenuItem itemCerrarAlmacen;
    private javax.swing.JMenuItem itemConsultarProducto;
    private javax.swing.JMenuItem itemCrearAlmacen;
    private javax.swing.JMenuItem itemEliminarProducto;
    private javax.swing.JMenuItem itemGuardarDatos;
    private javax.swing.JMenuItem itemListarProductos;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel labelAbierto;
    // End of variables declaration//GEN-END:variables
}
