all: principal contador calculador adivina

principal: principal.c
	cc -o principal principal.c

contador: contador.c
	cc -o contador contador.c

calculador: calculador.c
	cc -o calculador calculador.c

adivina: adivina.c
	cc -o adivina adivina.c

clean:
	rm principal contador calculador adivina fifo
