CREATE TABLE LOG 
(
  USUARIO VARCHAR2(50) NOT NULL 
, FECHA VARCHAR2(50) NOT NULL 
, OPERACION VARCHAR2(50) NOT NULL 
, TABLA VARCHAR2(50) 
, CONSTRAINT LOG_PK PRIMARY KEY 
  (
    USUARIO 
  , FECHA 
  )
  ENABLE 
);
