create or replace PROCEDURE pColaboradoresCaso (pCodCaso IN CASO_POLICIAL.CODCASO%TYPE, cursorCC OUT SYS_REFCURSOR) IS
BEGIN
    OPEN cursorCC FOR
    SELECT CODEXPERTO, EXPERTO.NOMBRE as NOMBRE_EXPERTO, ESPECIALIDAD, DESCRIPCION_COLABORACION  FROM COLABORA INNER JOIN CASO_POLICIAL USING(CODCASO) INNER JOIN EXPERTO USING(CODEXPERTO) WHERE CODCASO = pCodCaso;
END;