package lopez_pineda_borja;

public class Panel extends javax.swing.JFrame implements IObservador {

    public Panel(int numero) {
        initComponents();
        labelSala.setText("Panel Sala " + numero);
        labelPaciente.setText("");
        labelConsulta.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelSala = new javax.swing.JLabel();
        labelPaciente = new javax.swing.JLabel();
        labelConsulta = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setUndecorated(true);

        labelSala.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelSala.setText("Panel Sala N");

        labelPaciente.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelPaciente.setText("Paciente: Juan López Gómez");
        labelPaciente.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        labelConsulta.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelConsulta.setText("Consulta: 4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labelPaciente, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(labelSala)
                    .addComponent(labelConsulta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelSala)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelPaciente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelConsulta)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public void actualizar(String nombrePaciente, int consulta) {
        labelPaciente.setText("Paciente: " + nombrePaciente);
        labelConsulta.setText("Consulta: " + consulta);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel labelConsulta;
    private javax.swing.JLabel labelPaciente;
    private javax.swing.JLabel labelSala;
    // End of variables declaration//GEN-END:variables
}
