/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Aplicacion;

import Persistencia.colabora;
import Persistencia.conexionOracle;
import Persistencia.experto;
import Persistencia.manejaColabora;
import Persistencia.manejaExperto;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author borja
 */
public class ventanaColaboraciones extends java.awt.Frame {

    private final conexionOracle conexion;
    private final DefaultTableModel mColaboraciones;

    /**
     * Creates new form ventanaExpetos
     *
     * @param conexion
     */
    public ventanaColaboraciones(conexionOracle conexion) {
        initComponents();
        setLocationRelativeTo(getParent());
        setTitle("Tabla de expertos");

        this.conexion = conexion;

        mColaboraciones = new DefaultTableModel();
        jTableColaboraciones.setModel(mColaboraciones);
        String[] nombreColumnas = {"Descripción de Colaboración"};
        mColaboraciones.setColumnIdentifiers(nombreColumnas);
        jTableColaboraciones.getTableHeader().setResizingAllowed(false);
        
        manejaExperto me = new manejaExperto(conexion);
        try {
            ArrayList<experto> expertos = me.listaExpertos();
            for (experto experto : expertos) {
                jComboBoxExperto.addItem(experto);
            }
        } catch (SQLException ex) {
            Logger.getLogger(ventanaColaboraciones.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableColaboraciones = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jComboBoxExperto = new javax.swing.JComboBox<experto>();
        jLabel2 = new javax.swing.JLabel();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        jTableColaboraciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableColaboraciones);

        jLabel1.setText("Colaboraciones");

        jComboBoxExperto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxExpertoActionPerformed(evt);
            }
        });

        jLabel2.setText("Experto");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(166, 166, 166))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jComboBoxExperto, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE)
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jComboBoxExperto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        dispose();
    }//GEN-LAST:event_exitForm

    private void jComboBoxExpertoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxExpertoActionPerformed
        limpiarTabla();
        experto expertoSeleccionado = (experto)jComboBoxExperto.getSelectedItem();
        manejaColabora mc = new manejaColabora(conexion);
        try {
            ArrayList<colabora> colaboraciones = mc.listaColaboraPorExperto(expertoSeleccionado.getCodExperto());
            if(colaboraciones.isEmpty()){
                JOptionPane.showMessageDialog(null, "Este experto no tiene colaboraciones");
            }else{
                for (colabora colaboracion : colaboraciones) {
                    String[] fila = {colaboracion.getDescripcionColaboracion()};
                    mColaboraciones.addRow(fila);
                }
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_jComboBoxExpertoActionPerformed

    private void limpiarTabla() {
        while (mColaboraciones.getRowCount() > 0) {
            mColaboraciones.removeRow(0);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<experto> jComboBoxExperto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableColaboraciones;
    // End of variables declaration//GEN-END:variables
}
