package patronprototypepractica.interfaz;

import patronprototypepractica.Persona;
import patronprototypepractica.Mascota;
import patronprototypepractica.SerVivo;

public class MostrarSerVivo extends javax.swing.JFrame {

    public MostrarSerVivo(SerVivo serVivo) {
        initComponents();
        StringBuilder sb = new StringBuilder("<html><body>");
        sb.append("<b>Cabeza de familia: </b>").append(serVivo.getCabezaDeFamilia().getNombre()).append("<br>");
        sb.append("<b>Nombre: </b>").append(serVivo.getNombre()).append("<br>");
        sb.append("<b>Direccion: </b>").append(serVivo.getDireccion()).append("<br>");
        if(serVivo.getClass() == Persona.class){
            Persona persona = (Persona)serVivo;
            sb.append("<b>Apellidos: </b>").append(persona.getApellidos()).append("<br>");
            sb.append("<b>Teléfono: </b>").append(persona.getTelefono()).append("<br>");
            sb.append("<b>Código postal: </b>").append(persona.getCodigoPostal()).append("<br>");
            sb.append("<b>Ciudad: </b>").append(persona.getCiudad()).append("<br>");
            sb.append("<b>Nievel económico: </b>").append(persona.getNivelEconomico()).append("<br>");
            sb.append("<b>Correo electrónico: </b>").append(persona.getCorreoElectronico()).append("<br>");
            sb.append("<b>Nivel de estudios: </b>").append(persona.getNivelDeEstudios()).append("<br>");
            setSize(360, 250);
        }else if(serVivo.getClass() == Mascota.class){
            Mascota mascota = (Mascota)serVivo;
            sb.append("<b>Dueño: </b>").append(mascota.getDueno().getNombre()).append("<br>");
            setSize(360, 150);
        }
        sb.append("</body></html>");
        labelDatos.setText(sb.toString());
        setTitle("Datos de "+serVivo.getNombre());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelDatos = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        labelDatos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelDatos.setText("Datos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelDatos, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelDatos, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel labelDatos;
    // End of variables declaration//GEN-END:variables
}
