CREATE TABLE LOG (
  USUARIO VARCHAR2(100) NOT NULL,
  FECHA VARCHAR2(20) NOT NULL,
  OPERACION VARCHAR2(50) NOT NULL,
  TABLA VARCHAR2(50), CONSTRAINT LOG_PK PRIMARY KEY (
    USUARIO,
    FECHA 
  )
);
