/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "vector.h"

bool_t
xdr_t_vector (XDR *xdrs, t_vector *objp)
{
	register int32_t *buf;

	 if (!xdr_array (xdrs, (char **)&objp->t_vector_val, (u_int *) &objp->t_vector_len, ~0,
		sizeof (float), (xdrproc_t) xdr_float))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_entrada1 (XDR *xdrs, entrada1 *objp)
{
	register int32_t *buf;

	 if (!xdr_t_vector (xdrs, &objp->v))
		 return FALSE;
	 if (!xdr_float (xdrs, &objp->c))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_entrada2 (XDR *xdrs, entrada2 *objp)
{
	register int32_t *buf;

	 if (!xdr_t_vector (xdrs, &objp->v1))
		 return FALSE;
	 if (!xdr_t_vector (xdrs, &objp->v2))
		 return FALSE;
	return TRUE;
}
