/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package juegodados;

/**
 *
 * @author borja
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    private final Jugador jugador;
    private final DadoDoble dadosJugador, dadosBanca;
    private final Juego juego;
    public VentanaPrincipal() {
        initComponents();
        jugador = new Jugador(500);
        dadosJugador = new DadoDoble();
        dadosBanca = new DadoDoble();
        juego = new Juego(jugador, dadosJugador, dadosBanca, this);
        actualizarEstado("Realice una apuesta");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        labelSaldo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        fieldApuesta = new javax.swing.JTextField();
        btnApostar = new javax.swing.JButton();
        labelDadoJugador1 = new javax.swing.JLabel();
        labelDadoJugador2 = new javax.swing.JLabel();
        labelDadoBanca1 = new javax.swing.JLabel();
        labelDadoBanca2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        labelDadosJugador = new javax.swing.JLabel();
        labelDadosBanca = new javax.swing.JLabel();
        btnTirar = new javax.swing.JToggleButton();
        labelEstado = new javax.swing.JLabel();

        jLabel6.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        jLabel6.setText("1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Juego para ludopaters");

        jLabel1.setText("Saldo jugador:");

        labelSaldo.setText("jLabel2");

        jLabel2.setText("Dados jugador");

        jLabel3.setText("Dados banca");

        jLabel4.setText("Apuesta:");

        btnApostar.setText("Apostar");
        btnApostar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApostarActionPerformed(evt);
            }
        });

        labelDadoJugador1.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        labelDadoJugador1.setText("1");

        labelDadoJugador2.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        labelDadoJugador2.setText("1");

        labelDadoBanca1.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        labelDadoBanca1.setText("1");

        labelDadoBanca2.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        labelDadoBanca2.setText("1");

        jLabel5.setText("Resultado jugador");

        jLabel7.setText("Resultado banca");

        labelDadosJugador.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        labelDadosJugador.setText("2");

        labelDadosBanca.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        labelDadosBanca.setText("2");

        btnTirar.setText("Tirar dados");
        btnTirar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTirarActionPerformed(evt);
            }
        });

        labelEstado.setText("Realiza una apuesta");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelSaldo)
                        .addGap(50, 50, 50)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fieldApuesta, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnApostar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(49, 49, 49)
                                .addComponent(jLabel7))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(labelDadoJugador1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(labelDadoJugador2))
                                    .addComponent(jLabel2))
                                .addGap(80, 80, 80)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel3)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(labelDadoBanca1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(labelDadoBanca2))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(labelDadosJugador)
                        .addGap(126, 126, 126)
                        .addComponent(labelDadosBanca))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(btnTirar))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(labelEstado)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(labelSaldo)
                    .addComponent(jLabel4)
                    .addComponent(fieldApuesta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnApostar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDadoJugador1)
                    .addComponent(labelDadoJugador2)
                    .addComponent(labelDadoBanca1)
                    .addComponent(labelDadoBanca2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDadosJugador)
                    .addComponent(labelDadosBanca))
                .addGap(18, 18, 18)
                .addComponent(btnTirar)
                .addGap(18, 18, 18)
                .addComponent(labelEstado)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnApostarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApostarActionPerformed
        juego.apostar(Integer.parseInt(fieldApuesta.getText()));
        fieldApuesta.setText("");
    }//GEN-LAST:event_btnApostarActionPerformed

    private void btnTirarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTirarActionPerformed
        juego.tirarDaods();
    }//GEN-LAST:event_btnTirarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }
    
    public void actualizarDados(){
        labelDadoJugador1.setText(Integer.toString(dadosJugador.getDado1()));
        labelDadoJugador2.setText(Integer.toString(dadosJugador.getDado2()));
        labelDadoBanca1.setText(Integer.toString(dadosBanca.getDado1()));
        labelDadoBanca2.setText(Integer.toString(dadosBanca.getDado2()));
        labelDadosJugador.setText(Integer.toString(dadosJugador.getDados()));
        labelDadosBanca.setText(Integer.toString(dadosBanca.getDados()));
    }
    
    void actualizarEstado(String estado) {
        labelSaldo.setText(Integer.toString(jugador.getSaldo()));
        labelEstado.setText(estado);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApostar;
    private javax.swing.JToggleButton btnTirar;
    private javax.swing.JTextField fieldApuesta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel labelDadoBanca1;
    private javax.swing.JLabel labelDadoBanca2;
    private javax.swing.JLabel labelDadoJugador1;
    private javax.swing.JLabel labelDadoJugador2;
    private javax.swing.JLabel labelDadosBanca;
    private javax.swing.JLabel labelDadosJugador;
    private javax.swing.JLabel labelEstado;
    private javax.swing.JLabel labelSaldo;
    // End of variables declaration//GEN-END:variables

    
}
